defaults: &defaults
  working_directory: ~/api-node-axios-mocha
  docker:
    - image: circleci/node:latest

caches:
  - &npm_cache api-node-axios-mocha-v1{{ checksum "package.json" }}

references:
  restore_npm_cache: &restore_npm_cache
    restore_cache:
      keys:
        - *npm_cache

  npm_install: &npm_install
    run:
      name: Installing packages
      command: npm install

  save_npm_cache: &save_npm_cache
    save_cache:
      name: Save Npm Package Cache
      key: *npm_cache
      paths:
        - ~/.cache

version: 2.1

jobs:
  mocha:
    <<: *defaults
    steps:
      - checkout

      - <<: *restore_npm_cache
      - <<: *npm_install
      - <<: *save_npm_cache

      - run:
          name: Running tests
          command: npm test

      - store_artifacts:
          name: Saving report
          path: ~/api-node-axios-mocha/reports
          destination: /reports

workflows:
  version: 2.1
  build:
    jobs:
      - mocha
  nightly:
    triggers:
      - schedule:
          cron: "0 0 * * *"
          filters:
            branches:
              only: main
    jobs:
      - mocha
